"""se agrega campo code a building

Revision ID: f1121f6d456f
Revises: fbedc134b3ae
Create Date: 2025-11-12 13:56:15.596523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1121f6d456f'
down_revision: Union[str, Sequence[str], None] = 'fbedc134b3ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buildings', sa.Column('code', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buildings', 'code')
    # ### end Alembic commands ###
