"""initial schema

Revision ID: fbedc134b3ae
Revises: 
Create Date: 2025-11-12 13:31:58.143543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbedc134b3ae'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buildings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('floors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_floors_building_name_unique', 'floors', ['building_id', 'name'], unique=True)
    op.create_table('alerts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('floor_id', sa.Integer(), nullable=False),
    sa.Column('variable', sa.Enum('temperature', 'humidity', 'energy', name='variable_enum'), nullable=False),
    sa.Column('level', sa.Enum('info', 'medium', 'critical', name='alert_level_enum'), nullable=False),
    sa.Column('status', sa.Enum('open', 'acknowledged', 'closed', name='alert_status_enum'), nullable=False),
    sa.Column('message', sa.String(length=300), nullable=False),
    sa.Column('recommendation', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_floor_created', 'alerts', ['floor_id', 'created_at'], unique=False)
    op.create_table('metrics',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('floor_id', sa.Integer(), nullable=False),
    sa.Column('temp_c', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('humidity_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('energy_kw', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_metrics_floor_time', 'metrics', ['floor_id', 'time'], unique=False)
    op.create_table('thresholds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('floor_id', sa.Integer(), nullable=False),
    sa.Column('variable', sa.Enum('temperature', 'humidity', 'energy', name='variable_enum'), nullable=False),
    sa.Column('lower', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('upper', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('floor_id', 'variable', 'is_active', name='uq_active_threshold_per_var_floor')
    )
    op.create_index('ix_thresholds_floor_var', 'thresholds', ['floor_id', 'variable'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_thresholds_floor_var', table_name='thresholds')
    op.drop_table('thresholds')
    op.drop_index('ix_metrics_floor_time', table_name='metrics')
    op.drop_table('metrics')
    op.drop_index('ix_alerts_floor_created', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('ix_floors_building_name_unique', table_name='floors')
    op.drop_table('floors')
    op.drop_table('buildings')
    # ### end Alembic commands ###
